### PR TITLE
chore: Remove idea folder from npm

### PR DESCRIPTION
**Pull request by ffflorian**
~~Not everyone who clones this project uses WebStorm, therefore I vote to remove editor-specific files.~~

~~If you are using WebStorm, please use the [EditorConfig Plugin](https://plugins.jetbrains.com/plugin/7294-editorconfig).~~

Updated: The `.idea` folder is helpful for developing with WebStorm but should not be present when installing the client via npm.

### CODE REVIEW

**Comment by ffflorian** [comment]
VSCode is also one of the editors :wink:

**Comment by gregor** [comment]
@ffflorian Sure but do the WebStorm files break VSCode?

**Comment by ffflorian** [comment]
@gregor It doesn't, but I don't see the benefit of keeping it. But okay, it's not *that* important to argue about it. :wink: 

BTW, the folder is also distributed over npm and lands on user's HD when installing the API client, which is completely useless in my opinion. Can we at least settle on removing it from the npm release?

**Comment by bennyn** [comment]
@ffflorian Removing it from npmjs is a **must**. :)

**Pull request merged**
